spring:
  datasource:
#    #TODO 운영에선 mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
#    driver-class-name: org.mariadb.jdbc.Driver
#    password: 1128
#    url: jdbc:mariadb://localhost:3306/ajou_test?characterEncoding=UTF-8&serverTimezone=UTC
#    username: myadmin

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: ajouwithme@gmail.com
    password: ENC(vtQWfKf0nw1YGMvjUcLctu9uuUmZYp8fLC1FdbEqOho=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      springframework:
        web:
          filter: DEBUG
      hibernate.type: trace

#refreshKey: sdfhajks1u8924371389
#secretKey: sdjhfklashjf8927431892jnjksdah
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
refreshKey: ENC(b9WjPe3twebSpmOd8WIv8I8QqORGLWfbBP8v5mgkdPk=)
secretKey: ENC(wd+V9s5PRz1bDmHTDwBNLKvRfCAXHa/QmoBJeWImZd/Hdkd3e/Ysbw==)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

---

spring:
  config:
    activate:
      on-profile: "prod"